name: Deploy to GitHub Pages  # 工作流程名稱

on:
  push:
    branches: [ "main" ]  # 觸發條件：當代碼推送到 main 分支時運行

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 虛擬機環境

    steps:
      # 步驟 1：檢出代碼（將倉庫代碼下載到虛擬機）
      - name: Checkout repository
        uses: actions/checkout@v4  # 官方提供的檢出動作

      # 步驟 2：設定 Node.js 環境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"  # 指定 Node.js 版本

      # 步驟 3：安裝依賴（npm 或 yarn）
      - name: Install dependencies
        run: npm install  # 或使用 yarn install

      # 步驟 4：執行建置命令（生成靜態文件）
      - name: Build
        run: npm run build  # 執行 package.json 中的 build 腳本
        # 注意：這裡的 build 腳本需在 package.json 中定義（例如 "build": "vuepress build docs"）

      # 步驟 5：部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3  # 第三方部署動作
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 自動生成的權限 Token
          publish_dir: ./dist  # 指定要部署的靜態文件目錄（根據專案調整）
          # 其他可選參數：
          # cname: "yourdomain.com"  # 如果有自訂域名
          # keep_files: true         # 保留 gh-pages 分支的舊文件
